name: "⚠️ Bug report"
description: Report errors or unexpected behavior
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/Aarhus-University-MPE/Precipitation-Sampler/issues) before filing a new one!
  - type: input
    attributes:
      label: Precipitation Sampler Version
      placeholder: |
        0.1.1
      description: |
        Check software description
    validations:
      required: true

  - type: dropdown
    id: issueAreas
    attributes:
      label: Area(s) with issue?
      description: What things had an issue?  Check all that apply.
      multiple: true
      options:
        - Software
        - Master
        - Slave
        - Hardware
        - Sensors
        - Temperature
        - Motors
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including screenshots and a bug report log (System tray->Report bug).
      placeholder: Tell us the steps required to trigger your bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false
